# Generated by Django 4.0.6 on 2022-07-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devtool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('type', models.CharField(max_length=50, verbose_name='종류')),
                ('explain', models.TextField(verbose_name='설명')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('image', models.ImageField(blank=True, upload_to='ideas/%Y%m%d', verbose_name='이미지')),
                ('content', models.TextField(verbose_name='컨텐츠')),
                ('interest', models.IntegerField(verbose_name='관심도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_devtool', to='ideas.devtool')),
            ],
        ),
    ]
