# Generated by Django 4.0.6 on 2022-07-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('year', models.IntegerField(verbose_name='개봉년도')),
                ('genre', models.TextField(verbose_name='장르')),
                ('grade', models.FloatField(verbose_name='별점')),
                ('time', models.CharField(max_length=50, verbose_name='러닝타임')),
                ('review', models.CharField(max_length=300, verbose_name='리뷰')),
                ('director', models.TextField(verbose_name='감독')),
                ('actor', models.TextField(verbose_name='배우')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
