# Generated by Django 4.0.6 on 2022-07-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='actor',
            field=models.CharField(max_length=30, verbose_name='배우'),
        ),
        migrations.AlterField(
            model_name='review',
            name='director',
            field=models.CharField(max_length=30, verbose_name='감독'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
    ]
