# Generated by Django 4.0.6 on 2022-07-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_actor_alter_review_director_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='r_content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='time',
            new_name='r_time',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='year',
            new_name='r_year',
        ),
    ]
