# Generated by Django 4.0.6 on 2022-07-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_genre_alter_review_r_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='r_time',
            field=models.IntegerField(verbose_name='러닝타임'),
        ),
    ]
